volumes:
  redis-data:
    driver: local
  mysql-data:
    driver: local
services:
  app:
    build: .
    volumes:
      - ./config:/app/config
    ports:
      - 3000:3000
    depends_on:
      - mysql
      - captcha-resolver
      - redis
    environment:
      - PORT=3000
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=secure_mysql_password_2025
      - DB_DATABASE=payment_service
      - CAPTCHA_API_BASE_URL=http://captcha-resolver:1234
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    restart: always
  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=secure_mysql_password_2025
      - MYSQL_DATABASE=payment_service
      - MYSQL_CHARACTER_SET_SERVER=utf8mb4
      - MYSQL_COLLATION_SERVER=utf8mb4_unicode_ci
    volumes:
      - mysql-data:/var/lib/mysql
    # The ports section below is commented out to secure the database
    # ports:
    #   - 3306:3306
    restart: always
    command: --default-authentication-plugin=mysql_native_password
  captcha-resolver:
    image: registry.gitlab.com/nhayhoc/bank-captcha-server
    restart: always
  redis:
    image: redis:7-alpine
    # The ports section below is commented out to secure Redis
    # ports:
    #   - 6379:6379
    volumes:
      - redis-data:/data
    restart: always
