volumes:
  redis-data:
    driver: local
  postgres-data:
    driver: local
services:
  app:
    build: .
    volumes:
      - ./config:/app/config
    ports:
      - 3000:3000
    depends_on:
      - postgres
      - captcha-resolver
      - redis
    environment:
      - PORT=3000
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=payment_service
      - CAPTCHA_API_BASE_URL=http://captcha-resolver:1234
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    restart: always
  postgres:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=payment_service
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: always
  captcha-resolver:
    image: registry.gitlab.com/nhayhoc/bank-captcha-server
    restart: always
  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    restart: always
